javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private GameServer.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private GameClient.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private CheckPoint.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private Client.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private CoordinateSet.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private DisplayMessage.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private GameLogic.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private Opponent.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private Player.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private Position.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private TitleScreen.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private Vector2.java
javadoc -link https://docs.oracle.com/en/java/javase/15/docs/api/ -docencoding UTF-8 -charset UTF-8 -nonavbar -notree -noindex -nohelp -nodeprecatedlist -d Docs --module-path Addons\JavaFX\javafx-sdk-11.0.2\lib --add-modules=javafx.controls -private XMLSettings.java
pause